/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE 			0x40021000
#define GPIO_PA_BASE		0x40010800
#define RCC_APB2ENR			*((volatile unsigned int*)(RCC_BASE+0x18))
#define GPIO_PA_CRH 		*((volatile unsigned int*)(GPIO_PA_BASE+0x04))
#define GPIO_PA_ODR 		*((volatile unsigned int*)(GPIO_PA_BASE+0x0C))


int main()
{
	RCC_APB2ENR |= 1<<2;
	GPIO_PA_CRH &= 0xFF0FFFFF;
	GPIO_PA_CRH |= 0x00200000;

	while(1)
	{
		GPIO_PA_ODR |= 1<<13;
		for(int i=0; i< 5000; i++);
		GPIO_PA_ODR &= ~(1<<13);
		for(int i=0; i< 5000; i++);
	}
	return 0;
}
